#!/bin/bash
#
# Will run ../configure with either the given args or with the args
# used previously.
#
# Usage:
#   CONF
#   [env vars] CONF [args]
#
# When called without arguments and environment variables it will run
# ../configure with the previous arguments and variables, if those
# exist, or with empty arguments and variables otherwise.  It will not
# save empty arguments and variables.
#
# When called with arguments or environment variables it will run
# ../configure with those arguments and variables, and will save them
# for later use in ./CONF.txt.

if [[ $CC = "" && $CXX = "" && $AR = "" && $NM = "" && $RANLIB = "" && $@ = "" ]]; then
   if [ -f CONF.txt ]; then
      eval $(cat CONF.txt)
   else
      CONFARGS=""
   fi
else
   CONFARGS="$@"
   cat /dev/null > CONF.txt
   if [[ $CC != "" ]]; then echo "export CC='$CC'" >> CONF.txt; fi
   if [[ $CXX != "" ]]; then echo "export CXX='$CXX'" >> CONF.txt; fi
   if [[ $AR != "" ]]; then echo "export AR='$AR'" >> CONF.txt; fi
   if [[ $NM != "" ]]; then echo "export NM='$NM'" >> CONF.txt; fi
   if [[ $RANLIB != "" ]]; then echo "export RANLIB='$RANLIB'" >> CONF.txt; fi
   echo "export CONFARGS='$CONFARGS'" >> CONF.txt
fi
#echo $CC
#echo $CXX
#echo $AR
#echo $CONFARGS
../configure $CONFARGS
