#!/bin/bash
#
# Usage:
#   compile file

cat > compile-driver.sch << EOF
(for-each compile-file (cdr (vector->list (command-line-arguments))))
(exit 0)
EOF

larceny -quiet -nobanner -nofoldcase -- compile-driver.sch $@ 
if [ $? -ne 0 ]; then echo exit 1; fi
rm -f compile-driver.sch


