#!/bin/bash
#
# Usage:
#   swat (option | file) ...
#
# Input files must have a .swat suffix.  By default the output goes to
# a file with the same basename and a ".wast" suffix.
#
# Options:
#   -j
#   --js      Generate JS wrapping code, output goes to a .wast.js file
#
#   -s
#   --stdout  Print code on stdout, do not generate any files.
#
#   -f
#   --fail    Expect compilation failure, reverse exit codes
#
#   -h
#   --help    Print help text and exit.

cat > swat-driver.sch << EOF
(load "$(dirname $0)/swat.sch")
(exit (if (swat-noninteractive) 0 1))
EOF

larceny -quiet -nobanner -nofoldcase -- swat-driver.sch $@ 
if [ $? -ne 0 ]; then echo exit 1; fi
rm -f swat-driver.sch


