#!/bin/bash
#
# Usage:
#   swat (option | file) ...
#
# Input files must have a .swat suffix.  By default the output goes to
# a file with the same basename and a ".wast" suffix.
#
# Options:
#   -j
#   --js      Generate JS wrapping code, output goes to a .wast.js file
#
#   -s
#   --stdout  Print code on stdout, do not generate any files.
#
#   -h
#   --help    Print help text and exit.

cat > swat-driver.sch << EOF
(load "$(dirname $0)/swat.sch")
(swat-noninteractive)
(exit)
EOF

set -o pipefail
larceny -quiet -nobanner -nofoldcase -- swat-driver.sch $@ | grep -v 'larceny.heap, built on'
if [ $? -ne 0 ]; then exit 1; fi
rm -f swat-driver.sch


